### ISSUE TITLE
in Zen mode, right button press works inconsistently.

### ISSUE THREAD

**Issue by alebaho** [ddvk/remarkable-hacks#114]
in 2.4.1.30-patch_16.1.03-0-g43f55ec for rm1:
In Zen mode, pressing the right button usually toggles between two tools. Very practical if you need a pen and a highlighter combination too. This works fine as long as the left button (toggle between pen and eraser) is not pressed. If the left button is pressed, the right button loses the tool it was toggling to.
To recreate the issue: 
- Activate Zen mode; 
- Choose a highlighter in the tools; 
- Press the right button - the pen/highlighter alternate; 
- Press the left button to toggle the eraser; 
- Press the left button again to revert to pen/highlighter; 
- Press the right button to toggle between the pen or the highlighter. It does not work anymore.
As long as the left button (tool/error) is not pressed, the right button will alternate between the pen/highlighter.

**Comment by dstango** [comment]
seems also to relate to Lamy button confusing behaviour -- toggle last selected tools seems to be affected by the "hold to erase" function, too.

**Comment by ddvk** [comment]
a possible fix in 16.1.04

**Comment by dstango** [comment]
new update somewhat seems to break the Lamy button:
when I hold the button I can erase (I'm using hold to erase mode), but when I let go of the button it also toggles between the two tools. And one tool is always the eraser (don't know how I can change that :-(...).

**Comment by ddvk** [comment]
@dstango can't reproduce it. if the icons are: lamy button click, lamy togle last tool which means: hold to erase the behavious should be as it was (hold to erase and back to the pen)

**Comment by dstango** [comment]
thanks!
I tried again - it seems to work, sorry. I was somewhat confused by the button descriptions -- they describe actions, yet I was somewhat thinking they were descriping state. (actually I would prefer if they were showing state - like "Wifi disabled", "Lamy erases on hold", "First page shown", etc. -- so a simple view at the icons would tell me the current affairs without me needing to turn around everything in my head.)

But back to Lamy: What I hoped I could do was the following:
- click Lamy button to toggle between two tools
- hold Lamy button to erase until I release
- double click for undo

Is there a way to achieve this? Would be great :-). Thank you again for the great hacks!

**Comment by ddvk** [comment]
i can make this the default and remove the toggles as it seems they arw confusing

**Comment by Tridens92** [comment]
@ddvk, this works great now, and I agree the prior labels were confusing.  I do like dstango's suggestion to have the toggles list the CURRENT state rather than what they do, so that the toggle panel could show current state.  That means the toggles would be listed like this: 

[brackets] signify the alternate choice

Swipes: Disabled [Enabled]
Wifi: Disabled [Enabled]
Page Numbers: Hidden [Shown]
Bookmarks: Disabled [Enabled]
Pinch Zoom: Disabled [Enabled]
Buttons: Disabled [Enabled]
Last Opened Page: Shown [Hidden]
Battery: Shown [Hidden]

And then of course the Lamy toggles could come back to the panel with similar (Lamy button Erase: Hold [Press], etc.)

The alternate way to do this would be to add shading to the toggle background when it is enabled or disabled, and leave the button text static.  This might be more annoying though, as between screen refreshes there would be some artifacts/shadows left when the toggle panel is closed.

Even if the Lamy toggles don't return, I think setting up the toggle panel this way makes more sense, and gives a quick view of the status of each toggle rather than reading each toggle to discover it.  Further, it makes the toggles easier to locate, as the purpose of the toggle is the first word in the toggles (i.e. Wifi) rather than "Disable", etc.

In any case, as always, thanks for your work.  These Lamy additions have provided a HUGE increase in my productivity.
