### ISSUE TITLE
Configurable UI support

### ISSUE THREAD

**Issue by marcoms** [ddvk/remarkable-hacks#132]
This is a great project, but I personally would mainly be using it only to switch tools with the Lamy EMR button. Would it be possible to use a config file to disable extra features in the sidebar?

**Comment by rteusner** [comment]
Yes, I share your opinion. The remarkable stands out for its simplicity and lack of "clutter". With all the options added (which are great), the UX just gets cluttered. This prevented me from making the changes permanent. With this option, I would install it happily. 👍

**Comment by unphased** [comment]
why don't you use zen mode with sidebar hidden?

**Comment by rteusner** [comment]
Thank you for your response.

> why don't you use zen mode with sidebar hidden?

Perhaps I don't get the functionality right, as of now.
I am using a rM2 and could not make much sense of the Zen Mode as of now. I unfortunately also could not find a more detailed documentation what the Zen mode does.

I know that I can enter it with long pressing in the top right corner.
However for the rM2, I can see no benefit in that.

To toggle between pen and eraser, I can simply turn around the pen with the "Marker Plus".
My main concern is that if I need the sidebar, it is just "cluttered" with too many icons I do not need.
It just looks kind of crowded and poses visual disturbance, therefore I added my +1 for marcoms friendly request. 

Is there any other option to "simplify" the UI?

**Comment by unphased** [comment]
I've only had my rM2 for 2 days but i was able to work out some poorly doc'd / undoc'd functionality that makes zen mode more useful than any other mode. One is being able to swap between the 2 most recently used tools/pens by swiping down under the icon, the swipe left/right near the top in the middle (or thereabouts) to undo/redo, and swipe down in the non-top of the screen to toggle the menu, as well as being able to swipe to pan while zoomed in... you really do get most of the things you really need and can keep the menu closed all the time. 

You really want the menu closed all the time because the entire menu-wide column of the digitizer is inactive for the entire time the menu is up!

**Comment by unphased** [comment]
i suppose it is very beneficial to follow the tutorial that base xochitl presents to you when you start up the original software. this patch is like the xochitl prestige mode, i'm super impressed.

**Comment by ddvk** [comment]
added a toggle switch

**Comment by katiebobus** [comment]
Sorry, toggle switch for what? Is it in the menu?

**Comment by ddvk** [comment]
yes, in the share menu

**Comment by katiebobus** [comment]
Sorry, unclear what toggle was added..

Could someone post a video of the tool switch/eraser gestures in action? I keep trying swiping vertically under the icon and I just can't find these.

**Comment by ddvk** [comment]
https://imgur.com/a/x19iBZM

**Comment by evando1189** [comment]
has this functionality changed in the newer patches? I don't see a toggle switch in the share menu and pressing the button will only switch between the pen and the select tool. Is there a way to make it so that press and hold uses the eraser, a single click uses the erase selection tool, and double click is undo?

**Comment by ddvk** [comment]
disable extra feature is the UI (Extra off)

**Comment by evando1189** [comment]
I'm sorry, I don't fully understand your comment. Admittedly I am new to your code, I just installed the hack this morning, but after deep diving into notes and forums and reddit, it seems that at some point there was a toggle switch in the new menu that you could adjust the functionality of the button on the Lamy pen. I don't see this toggle switch in my menu so I was just wanting to know if that was removed at some point.

I so see the ExtraUI toggle button, if that's what you're referring to.
