### ISSUE TITLE
Feature request: swipe left/right in upper right corner in Zen mode to change colors

### ISSUE THREAD

**Issue by Cindy-Jie-01** [ddvk/remarkable-hacks#163]

**Comment by ddvk** [comment]
i can off swipe up for now for switching the last 2 colors

**Comment by ZacharieALES** [comment]
I really like this feature, thanks!

I never use white so I would have a preference for a toggle between the two last colors (but I like it anyway!).

**Comment by Tridens92** [comment]
Perhaps I'm doing something wrong, but I can't get this to work.  When I try to swipe up from the upper corner, it just closes the open menu.  Sometimes I see the circle color around the pen size briefly change before the menu closes, but it doesn't seem to actually change the pen.  I'm a left-handed user, but I've tried in both left and right handed UI mode and have similar problems.

Also, wouldn't it make more UI sense to change this swipe up action to function over the pen size selector rather than the upper corner? (unless the intention is for people to be able to use it when the menu is closed/zen mode)

**Comment by sersorrel** [comment]
the point's definitely for use in zen mode. swiping _up_ shouldn't close the menu, fwiw; having just tried – swiping upwards in the top corner, opposite side of the page to the menu – it works fine for me in both right-handed and left-handed mode.

**Comment by Tridens92** [comment]
Thanks for the input and test, @sersorrel.  However, this is definitely not working for me.  Before I was trying to swipe from the menu side (as the patch notes weren't clear about which side to swipe from).  But even swiping from the other side doesn't change the marker color for me.  I'm using an rM1, Version 2.5.0.27-patch_17.1.05

**Comment by Tridens92** [comment]
Thanks, @sersorrel.  I was able to make this work by swiping from much lower than the "upper corner".  And I had been swiping from the menu side, not the blank side, as the patch notes weren't clear for lefties.

**Comment by ddvk** [comment]
closing as fixed
