### ISSUE TITLE
Time zones "Etc/GMT+n" flipped + and -

### ISSUE THREAD

**Issue by sakabug** [ddvk/remarkable-hacks#229]
Time zones "Etc/GMT+n" have (+) and (-) flipped.

**Comment by ddvk** [comment]
ill have to check, i think i just exported them from my linux box

**Comment by ddvk** [comment]
so, you mean that the Etc/GMT-6 is actually Et/cGMT+6? this apparently by design and it's just how it is on the tablet.

https://stackoverflow.com/questions/7303580/understanding-the-etc-gmt-time-zone#:~:text=offset%20of%20zero.-,What%20exactly%20is%20the%20Etc%2FGMT%20time%20zone%3F,in%20their%20offset%20over%20history.

https://opensource.apple.com/source/system_cmds/system_cmds-230/zic.tproj/datfiles/etcetera
