### ISSUE TITLE
Problems reinstalling after 2.6 update

### ISSUE THREAD

**Issue by posi4life** [ddvk/remarkable-hacks#257]
Hi, after the 2.6 update I tried to reinstall the hack and got this error message:

![image](https://user-images.githubusercontent.com/81441600/112684161-e5ef1900-8e72-11eb-8709-10e0be744fa2.png)

What can be done to solve this issue?

Kind regards.

Jan

**Comment by Eeems** [comment]
Looks like your root partition is full. You'll have to figure out why that is and try to free up some space. The script already tried to clear space with log files and couldn't clear anything up.

**Comment by posi4life** [comment]
I did a factory reset but this message still appears. How can the partition be full? How can I check that?

**Comment by Eeems** [comment]
Factory reset doesn't do what you think it does. It will not clear the root partition. You'll need to poke around to see what's happened.

**Comment by posi4life** [comment]
Just made the update, I didn´t change anything else, I don´t know where to free space. But thanks for your help.

**Comment by Eeems** [comment]
On my rM1 the root partition has 18.1MB free. I would suggest double checking what yours is reporting by running `df -h`. Do you have a specific version number that you are running?

**Comment by posi4life** [comment]
It says 100% full, I am on version 2.6.2.75. How can I access the root partition to check it?

**Comment by Eeems** [comment]
The root partition is mounted to `/`. Take a look at the output of `mount` to see the list of what is mounted below that, so you can ignore things like `/home`

**Comment by posi4life** [comment]
I am connected via WinSCP and I can see the file structure but don´t know how I can free up space to reinstall the hack

**Comment by Eeems** [comment]
I would suggest connecting via an SSH client like putty.

**Comment by posi4life** [comment]
When I type mount I get this
![image](https://user-images.githubusercontent.com/81441600/112696402-0bd1e900-8e86-11eb-8cc1-089de5e59c39.png)

**Comment by Eeems** [comment]
So that tells you what to ignore when looking into what is taking up all the space on `/`. So you can ignore `/dev`, `/sys`, `/proc`, `/run`, `/tmp`, `/var/volatile`, `/var/lib/uboot`, and `/home`. I would suggest using `du -hs <path>` to figure out the size of folders to see what might be using more than you'd expect. Replace `<path>` with the path to the folder, i.e. `du -hs /etc`.

If you would like to see what the sizes of the folders were on the previous version to compare, you can mount it to `/mnt` with the following command: `mount /dev/mmcblk2p3 /mnt` and then run `du -hs /mnt/*` to get the full list. After which you can unmount it with `umount /mnt`

**Comment by ddvk** [comment]
did you install any sleepscreens or templates?

**Comment by posi4life** [comment]
Yes, I had some user templates on the device before the update but they are gone also

**Comment by posi4life** [comment]
I deleted all the user templates and now it worked. Thank you all for your help, really appreciated!
