### ISSUE TITLE
remote host key issue 

### ISSUE THREAD

**Issue by katiebobus** [ddvk/remarkable-hacks#265]
Apologies if this is the wrong forum for personal tech support (happy to remove and post elsewhere if you can enlighten me where). Got the 2.6 update (rM2), trying to reinstall hacks and I get the "remote host identification has changed" warning with the fingerprint for the RSA key and offending RSA key (line 1 of known_hosts). 

I'm just using Windows command, though I can install putty. I used ssh-keygen -R 10.11.99.1, which let me re-enter the ssh root command (with my rM password) -- but then I get a prompt to enter the host password. I figured I was SOL at this point but I tried re-entering the rM root password and got "command not recognized."  

Where am I going wrong?? I need someone to walk me through with the code bc I am a n00b.

Much thanks in advance,
K

**Comment by pstemper** [comment]
This really has nothing to do with the patch.

This is an "issue" with using the windows SSH shell.  When you use it the first time to connect to the reMarkable, a "key" exchange happens between the SSH shell and the reMarkable.  This key is stored on your windows PC, and is used to ensure that the next time you connect to the rM, you are connecting to the same rM.  Now, when you apply a reMarkable update, the key on the reMarkable changes.
When you try to re-apply the patch after the 2.6 update, Windows SSH compares the previous key with the new one the rM sends, and since they are different, the connect fails.
To fix this, you can delete the "old" key from your machine.
The key (when using Windows SSH) is located in c:\users\<username>\.ssh in a file called known_hosts, where <username> is your local login name on your machine.
So, for example, I am logged into my machine as pstemper.  In my case the file is in a directory called c:\users\pstemper\.ssh\
If you delete that known_hosts file, and then restart ssh, your should be able to connect again.
NOTE: the .ssh subdirectory my NOT be visible on your machine if you have system files/folders hidden..

Paul

**Comment by katiebobus** [comment]
Thanks (and yes, apologies - I am aware it's not a patch issue, merely an issue I discovered while trying to install the patch). I really appreciate the troubleshooting. 

I'm still having issues. I deleted the host file from my local ssh folder and restarted the rM2. Here's what I get now:

M:\>ssh root@.10.11.99.1 [my pword]
The authenticity of host '10.11.99.1 (10.11.99.1)' can't be established.
RSA key fingerprint is SHA256:LYDA32qoE61cDFVLRJNZSNsvDTp3l9AeBdHpFqiLfJA.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '10.11.99.1' (RSA) to the list of known hosts.
root@10.11.99.1's password: [I enter the root pword]
sh: [my pwd]: command not found

**Comment by pstemper** [comment]
Can you try this?
1) Delete the known_hosts again.
2) At the command prompt (the m:) type "ssh root@10.11.99.1" (without quotes), and press enter.  The line you showed had an extra period after the root@..
3) Answer "yes" (without quotes) at the "Are you sure you want to continue connecting" prompt, just like you showed.
4) When it asks for the passwword, enter the password for your rM device, and press enter.

Let us know if that lets you in.
Paul

**Comment by katiebobus** [comment]
ok that fixed it! THANK YOU!! (note: I didn't actually have the extra . there - I created that typo, so it was that the shell didn't want the password in the command line. Windows is so stupid.)

**Comment by pstemper** [comment]
Glad it is working!  When I saw your text that showed "root@10.11.99.1's password:" I was wondering if you were including the password on the SSH line.  ;)

Can you close this ticket now?
Thanks!

Paul

**Comment by katiebobus** [comment]
Yes - thanks again!
