### ISSUE TITLE
update to version 2.7.1.53

### ISSUE THREAD

**Issue by leinad152** [ddvk/remarkable-hacks#304]
Hello, ist it possible to update your hack to version 2.7.1.53? It is such a helpful hack! Thanks a lot!

**Comment by ddvk** [comment]
is this an official version or some beta?

**Comment by leinad152** [comment]
Don't know for sure. It could be a beta. How can I find out whether it is the one or the other?

Thank you for your answer and the time!

**Comment by leinad152** [comment]
My remarkable just received the update and your hack is gone as expected. But it is impossible for me to reinstall the hack due to the different version of the software. Do you need the original note from the command - window?

**Comment by ddvk** [comment]
did you enter the beta? 

porting takes time, and the betas change too often, so it is a waste of time

**Comment by leinad152** [comment]
Actually, it seems I did agree to join the beta-testing. Sorry for bothering you with my request! Is there a way to undo the update? I have unenrolled from the testing. Thanks In advance!

**Comment by pstemper** [comment]
There is a way, depending on how "comfortable" you feel in the linux universe.
There are TWO partitions used in the remarkable for storing the OS.  One is the current partition, the other is the previous partition (before your last update.)  You can switch back to the previous partition (from hopefully before the beta version got installed), and then turn off the beta enrollment.  Issue #287 talks about the partitions, and how you can switch.  I switched back from a beta to the last full version using this technique because I too could not live without the DDVK hacks!  This does NOT affect the data partition, where your actual "notebooks" are stored, so it will not affect those.  It only affects the OS partitions.

Paul

**Comment by dstango** [comment]
the rmhacks also store a backup copy of the original file -- you might use that to revert the version, especially as it seems to be a minor bug fix which hopefully doesn't change any file structures.
Check out the section "Revert in case things go terribly wrong" in the remarkable-hacks README.md

**Comment by leinad152** [comment]
Hello dstango, thanks, but that didn't work. 

Now, I would like to change the partition, but alas, Im' not familiar enough with the Linux Universe to know where to execute those commands you gave in issue #287. Untiul now I have only worked with the Windows-Command window and did put in executable commands like the installation of your hack.

I guess, I just have to wait until there will be another official version and the hack will be adapted to that. 

Thank you for all the effort!

**Comment by pstemper** [comment]
dstango, yeah, I also tried reverting back by just using the backup version, and that failed for me also.  It appears that when you are part of the beta, it somehow uses a different XOCHITL then the one it normally uses (I did "restore" the XOCHITL from the backup and verified it was the correct one, but the beta version continued to be used, so it was somehow pointing to a different file then the "normal" XOCHITL.  Instead of wasting time trying to figure out where the beta version was installed (or what other things the beta configuration had changed), I just reverted to the old partition as stated in #287.  I really could NOT live without the DDVK hacks since I have been using them for so long.  Too useful to be without!!  (Thanks ddvk!!)

leinad152, it really isn't that hard to go to the alternate partition.  I did it using a windows SSH session, I just made sure I typed the commands carefully (reviewed them twice before hitting enter ;) ) and it worked without a hitch.  If you want me to walk you through it (if you just can't live without the ddvk hacks), let me know and I can write up the steps I used.  Not too difficult.

**Comment by leinad152** [comment]
pstemper, actually, a little help would be very good. I just don't know how to start (by simply opening an ssh-connection?) or how to input the whole, several lines of programming. Sorry, I'm still a rookie with this. I'd like to give it a try though. One lives and learns...

**Comment by pstemper** [comment]
No problem!
Start an ssh session with the remarkable (just like you did to apply the patch).  Once logged in, at the prompt type the following line, and press enter to execute it.

fw_setenv "bootcount" "0"

That line will "reset" the boot count (after a certain number of failed boots, the system will assume there is a problem with the boot process and try to recover.  We want to reset that count to avoid that this time.)
Next type the following line (and press enter to execute it).

fw_printenv -n active_partition

This will display either a number 2 or a number 3.  This indicates the CURRENT active partition.  Record this number as we will use it on the next line.  Type the line below, replacing the ACTIVEPARTITIONNUMBER with the number you recorded above (and again press enter)  NOTE: There are QUOTES around the partition number.  Don't forget those.:

fw_setenv "fallback_partition" "ACTIVEPARTITIONNUMBER"

This tells the system that the current partition (the one currently booted, and containing the BETA code) is now the "backup" partition.
Now, if the number recorded above (ACTIVEPARTITIONNUMBER) was 2, then we want the new partition to be 3.  If the number above was 3, then we want the new partition to be 2.  Record this number, as we will be using it in the next command line.  Now type the line below, replacing NEWNUMBERHERE with the new number we just recorded, and press enter to execute it.

fw_setenv "active_partition" "NEWNUMBERHERE"

This tells the system that the partition we want to run from next time we reboot is the "other" partition, which should be the partition that had your "pre-beta" operating system.  Finally, type the line below and press enter to execute it.  This will reboot the remarkable.

reboot


Now, once the remarkable has rebooted, go and opt out of the beta test enrollment right away, before your remarkable applies the beta image again (Settings->General->click on the software version box->Unroll (misspelled)) .  This is important to do RIGHT AWAY, otherwise it will apply the beta image to this newly active partition, and then BOTH of your partitions would contain a beta version and you can't switch to a non-beta version untill the next official release of the OS :)

So for example, lets assume I am currently on partition 3, my session would look something like this:
fw_setenv "bootcount" "0"
fw_printenv -n active_partition
(this above line would return 3 in my example)
fw_setenv "fallback_partition" "3"
fw_setenv "active_partition" "2"
reboot

Then I would go and un-enroll in the beta.

At this point, you should see you are no longer on a beta version of the software.  So, now you can follow the usual steps to apply the DDVK patch again if needed.  You may not need to as your old partition may have already had the DDVK patch.

Let me know if you have any questions, and I hope this helps.  Just read this all through, make sure you understand the steps, take a deep calming breath, and type everything correctly (watch you spelling of the command lines.)

**Comment by leinad152** [comment]
Wow, thanks a lot! I will try this tomorrow and let you know how it went. You even explained everything. That does make it more clear and less "magic" if you know what I mean by that.

**Comment by pstemper** [comment]
I definitely understand what you mean!  I typically don't like telling people just to type something, I want them to learn what they are doing.  The old adage of "teach a man to fish"...
Yes, please let me know how it works for you tomorrow, or if you encounter any questions as you attempt it.

**Comment by pstemper** [comment]
Fantastic!!  I am glad it worked for you!
You can close the issue yourself through the GitHub web interface when you're viewing the issue. The "Close Issue" button is to the left of the "comment" button under the comment box.

**Comment by CrazyEasy** [comment]
> is this an official version or some beta?

It is now available as an official release

**Comment by martin-braun** [comment]
> No problem!
> Start an ssh session with the remarkable (just like you did to apply the patch). Once logged in, at the prompt type the following line, and press enter to execute it.
> 
> fw_setenv "bootcount" "0"
> 
> That line will "reset" the boot count (after a certain number of failed boots, the system will assume there is a problem with the boot process and try to recover. We want to reset that count to avoid that this time.)
> Next type the following line (and press enter to execute it).
> 
> fw_printenv -n active_partition
> 
> This will display either a number 2 or a number 3. This indicates the CURRENT active partition. Record this number as we will use it on the next line. Type the line below, replacing the ACTIVEPARTITIONNUMBER with the number you recorded above (and again press enter) NOTE: There are QUOTES around the partition number. Don't forget those.:
> 
> fw_setenv "fallback_partition" "ACTIVEPARTITIONNUMBER"
> 
> This tells the system that the current partition (the one currently booted, and containing the BETA code) is now the "backup" partition.
> Now, if the number recorded above (ACTIVEPARTITIONNUMBER) was 2, then we want the new partition to be 3. If the number above was 3, then we want the new partition to be 2. Record this number, as we will be using it in the next command line. Now type the line below, replacing NEWNUMBERHERE with the new number we just recorded, and press enter to execute it.
> 
> fw_setenv "active_partition" "NEWNUMBERHERE"
> 
> This tells the system that the partition we want to run from next time we reboot is the "other" partition, which should be the partition that had your "pre-beta" operating system. Finally, type the line below and press enter to execute it. This will reboot the remarkable.
> 
> reboot
> 
> Now, once the remarkable has rebooted, go and opt out of the beta test enrollment right away, before your remarkable applies the beta image again (Settings->General->click on the software version box->Unroll (misspelled)) . This is important to do RIGHT AWAY, otherwise it will apply the beta image to this newly active partition, and then BOTH of your partitions would contain a beta version and you can't switch to a non-beta version untill the next official release of the OS :)
> 
> So for example, lets assume I am currently on partition 3, my session would look something like this:
> fw_setenv "bootcount" "0"
> fw_printenv -n active_partition
> (this above line would return 3 in my example)
> fw_setenv "fallback_partition" "3"
> fw_setenv "active_partition" "2"
> reboot
> 
> Then I would go and un-enroll in the beta.
> 
> At this point, you should see you are no longer on a beta version of the software. So, now you can follow the usual steps to apply the DDVK patch again if needed. You may not need to as your old partition may have already had the DDVK patch.
> 
> Let me know if you have any questions, and I hope this helps. Just read this all through, make sure you understand the steps, take a deep calming breath, and type everything correctly (watch your spelling of the command lines.)

Great work @pstemper. I think it might be worth to put this in the README to teach the people about downgrading right away? @ddvk

**Comment by pstemper** [comment]
When I get some time, I will submit a PR and help update the readme.

**Comment by Eeems** [comment]
It would probably be better to put this in https://remarkablewiki.com and then link to it from the readme.

**Comment by pstemper** [comment]
@Eeems You are probably right.  It isn't specific to the hacks, more of an rM operational thing..

**Comment by martin-braun** [comment]
@Eeems Thanks for sharing this website, I wasn't aware of it and I agree, makes more sense to post it in a general location and link to it, instead.

**Comment by Tridens92** [comment]
@pstemper , I was surprised to see my tablet update to 2.9 even though I'm religious about making sure auto-update is off.  Not sure how that happened, but in any case, I followed your directions to restore the backup partition and I'm back in business with ddvk's hack.  Can't live without it.  Thanks so much for providing these directions.  I was NOT looking forward to 5 hours of client meetings tomorrow without my hacks and my Lamy erase button!

**Comment by pstemper** [comment]
@Tridens92 No problem!  Glad it worked for you, and that I could help!!

Paul

**Comment by Eeems** [comment]
For anybody finding this now that it's been years later. Please go look at https://remarkable.guide/faqs.html#can-i-downgrade-to-a-different-os-version instead of following dated instructions here.

@ddvk it might be worth collapsing the outdated instructions (I know they technically aren't outdated, but somehow people have found them and soft-bricked their device).
