### ISSUE TITLE
Have you considered how this might work on reMarkable 2?

### ISSUE THREAD

**Issue by PhilT** [ddvk/remarkable-hacks#31]
As the rM2 won't have buttons it'll have to all be done with gestures.

**Comment by dstango** [comment]
If you look at the recent updates of these hacks you'll find that more and more gestures are added that mirror the functionality achieved by keys on rm1.
(Personally the lack of some hardware buttons on rm2 is a showstopper for me. Already on rm1 gestures activate annoyingly by accident while writing [thanks for the option to disable them in the hack!!!] --- and personally I'm not just a "paper person" but also a "button person" because buttons provide some haptic feedback on what I'm doing ...)

**Comment by PhilT** [comment]
Yeah, I know what you mean. I've noticed accidental page turns now and again. I think they'll be forced to improve gestures a lot though once the rM2 is out otherwise they'll get a lot of complaints. I always liked that you could rest you palm on the rM1 while writing until they added gestures but it doesn't happen all the time so I live with it.

What is the source language used? Would you be interested in sharing it so that perhaps I could make a version for the rM2 once it's out?

**Comment by ddvk** [comment]
i've considered the rm2, that's why you can do everything without the buttons (except switch between pen/eraser), i personally rarely use the buttons.

imho the rm2 will use the exact same software, toolchain etc, but I will know for sure when I hopefully get mine in August.

sure, the swipe gestures can be optimized further to prevent accidental page turns (some minor adjustments to the velocity / swipe length should do it)

the source language is nothing fancy, just qml/js/c++ + some assembly, I would love to share, but as I've already stated, this violates some EULAs  and the legality is a grey area. you can reach out to remarkable and if they are ok with me giving access to other people...

**Comment by PhilT** [comment]
So it seems like you have considered it. Of course pen/eraser won't be an issue on rM2 (at least if you have the marker plus). I guess the only other one could be undo but could probably live without that. If anything else comes up I will be sure to speak to remarkable to get permission.

It's a great set of patches by the way. Should totally be the default. Thanks.

**Comment by Utopiah** [comment]
> the source language is nothing fancy, just qml/js/c++ + some assembly, I would love to share, but as I've already stated, this violates some EULAs and the legality is a grey area. you can reach out to remarkable and if they are ok with me giving access to other people...

Well the source from reMarkable is problematic but your own code? I don't see why this could be a problem to share solely the diff. That code have nothing to do with reMarkable, it just runs on their platform.

**Comment by jtremback** [comment]
I just sent them this in their contact form:

> Hello, I have been using the excellent "Remarkable Hacks" 3rd party extensions on my RM1 (https://github.com/ddvk/remarkable-hacks). I understand that this is completely at my own risk and that you do not support it etc etc. The author of "Remarkable Hacks" feels that they cannot open source it since it might violate your EULA (https://github.com/ddvk/remarkable-hacks/issues/31#issuecomment-641116783). This has stopped me from being able to help on its development. One of the big reasons I got a ReMarkable instead of a Ratta Supernote, even though the Ratta has more software features, is that ReMarkable currently has a strong community of 3rd party open source developers. Allowing the author of "Remarkable Hacks" to open source their work would help you keep this position. Is this something you'd consider?

**Comment by jtremback** [comment]
Got this response

> Hello.

At reMarkable, we are happy to see the enthusiasm surrounding our products and services. However, we cannot at this stage grant permission to violate the EULA. We hope for your understanding.

Best wishes.
Jon
Tech Support Agent
Your reMarkable Team
www.remarkable.com

**Comment by ddvk** [comment]
Sorry to hear that,

patches are a gray area, but i'm not distributing the software per se.
As for modifying, it says: "... to the extent permitted by law ...." which in my case is:  The 
 engineering, which can be operated by the owner of the software or by an authorized third party, is however limited by law to the case of obtaining necessary information for the development or use of interoperable software and this information cannot be disclosed to unauthorized third parties
