### ISSUE TITLE
Install issue, TLS certification validation failed

### ISSUE THREAD

**Issue by LuYutum** [ddvk/remarkable-hacks#326]
![image](https://user-images.githubusercontent.com/74893197/124534577-203f5d80-de47-11eb-9d29-5ac83dc32409.png)

**Comment by ddvk** [comment]
the wget version on the devices doesn't do certificat validation. the rest seems to be a connectivity problem, what kind of access point are you using

**Comment by cgr02** [comment]
I also had some problems in trying to install specific patches (no problems with the master patch). This is the message I get:
![rM2 server returned error](https://user-images.githubusercontent.com/77006047/124632907-0ae92400-de85-11eb-9947-e47c17b80ccb.png)
I don't think it should be a connectivity problem for me since I'm able to install the master patch, but I'm not really sure. Thank you for your work!

**Comment by LuYutum** [comment]
> the wget version on the devices doesn't do certificat validation. the rest seems to be a connectivity problem, what kind of access point are you using

This could indeed be a internet connection problem. My device is connected to the internet but it doesn't sync. Thank you, and i'll try some other access points later.
