### ISSUE TITLE
Feature Request: Display local IP adress on the main menu

### ISSUE THREAD

**Issue by naturale0** [ddvk/remarkable-hacks#390]
Wirelessly connecting to rM devices will be much easier if the local IP address is visible on the home screen.

Since the local IP (something like 192.168.xxx.xxx) is changing frequently even connected to the same network, It would be very helpful to have the address displayed somewhere on the main menu.

If displaying the IP to the main menu is difficult, then it might be helpful to be able to see it in the menu bar (toggle between time and local IP).

(_Originally posted by @naturale0 in https://github.com/ddvk/remarkable-hacks/issues/387#issuecomment-983324801_)

**Comment by Eeems** [comment]
You could also just assign your tablet a static IP address on your wireless router.

**Comment by martin-braun** [comment]
@Eeems Not everybody has this setup though. For instance, I use my mobile hotspot with unlimited bandwidth and own no router.

**Comment by Eeems** [comment]
Ah, in that case, just use USB and connect over that instead.

**Comment by Eeems** [comment]
I find that the USB interface is much faster and more stable than using WiFi for interacting with the reMarkable.

**Comment by naturale0** [comment]
I don't know what seems to be the problem of desiring easier access. @Eeems suggest two solutions: (1) Use a router setup or (2) connect via USB. 

(1) is useful if you are usually on a single, configurable network. However, I (and presumably most of the users) move around between at least three different networks, two of which are definitely not configurable: lab network & mobile hotspot (not rooted).

(2) is not a solution. I know I can always get a reliable and fast wired connection. I just find it much more joyful to have cables off of my desk. Especially when streaming the screen while writing, which I do routinely, no cable on desk means less distraction, more productivity.

**Comment by Eeems** [comment]
> lab network & mobile hotspot (not rooted).

I assume that you also include work networks in lab network.

> I don't know what seems to be the problem of desiring easier access.

Nothing is wrong with wanting easier access. It just feels like bloat for this project. The more things you add, the longer it takes to port changes between releases.

> (2) is not a solution. I know I can always get a reliable and fast wired connection. I just find it much more joyful to have cables off of my desk. Especially when streaming the screen while writing, which I do routinely, no cable on the desk means less distraction, more productivity.

Just because you don't like the aesthetics of a solution doesn't mean it isn't a solution. It's just not one you like.

A third solution is that you use a launcher and write a simple application that just displays IP addresses so it's quicker to get at. I've written a tutorial in the past for how to write applications with SAS that could be used to accomplish this: https://eeems.website/writing-a-simple-oxide-application/

**Comment by naturale0** [comment]
> Just because you don't like the aesthetics of a solution doesn't mean it isn't a solution. It's just not one you like.

The whole point of this request is to have a way to make wireless connections more accessible, not heading back to the wired one. Your second suggestion is definitely not about wireless connection at all.

> Nothing is wrong with wanting easier access. It just feels like bloat for this project. The more things you add, the longer it takes to port changes between releases.

I do understand such tradeoffs. It is just a small request and a question to a developer and the community who made me love my rM more. I thought It might change how we use the device daily (which is the point of hacks), yet the implementation might not be that hard. Though for the latter I am purely guessing.

I will definitely try the third suggestion if my request is indeed a hard-to-be-accepted one. Thank you for the resource!

**Comment by Eeems** [comment]
> The whole point of this request is to have a way to make wireless connections more accessible, not heading back to the wired one. Your second suggestion is definitely not about wireless connection at all.

A solution that has nothing to do with the original ask, but addresses the root cause is still a solution. I've found that quite often I've been asked for a specific solution by clients because they think it is the right solution for the business need they have. When what they actually need is something completely different, that solves the business need way better than the technical solution they were asking for.

> I do understand such tradeoffs. It is just a small request and a question to a developer and the community who made me love my rM more. I thought It might change how we use the device daily (which is the point of hacks), yet the implementation might not be that hard. Though for the latter I am purely guessing.

Who knows, maybe @ddvk will want to implement it. I'd recommend against it for him though, as these hacks are already big enough for porting to new versions.


> I will definitely try the third suggestion if my request is indeed a hard-to-be-accepted one. Thank you for the resource!

Feel free to reach out on the community discord or the comments section of the linked article if you need more help.

Some important information you'll want to be aware of:

- Install an SSH key for access to avoid issues if the root password gets rotated.
  - You will need to buy physical hardware to recover if you lose access to the UI and SSH: https://github.com/ddvk/remarkable2-recovery
  - Avoid factory resetting when you run into issues: https://remarkablewiki.com/trouble/factory-reset
- Turn off automatic updates to avoid losing your workflow with OS upgrades that break things.
  - Toltec doesn't stop you from installing on an unsupported OS yet: https://github.com/toltec-dev/toltec/issues/445
  - You can downgrade if this happens: https://github.com/ddvk/remarkable-update

**Comment by ddvk** [comment]
tbh, i just use the hostname (remarkable) which my router running dnsmaskq registers

**Comment by matteodelabre** [comment]
You could also make a basic script that runs in the background, monitors the wlan connection state, and prints the current IP to the screen. In fact, I just wrote such a script! <https://gist.github.com/matteodelabre/91f02eee2904c5f0cb75f0847ec045f9> It needs `fbink` (a package is available in Toltec). It’s a bit crude, but it works.

**Comment by naturale0** [comment]
@matteodelabre It does exactly what I need. Such a solution. Thank you for sharing!
