### ISSUE TITLE
Feature Request: Battery Status on toolbar

### ISSUE THREAD

**Issue by PkW4v3** [ddvk/remarkable-hacks#44]
Could you add battery status on the toolbar?
I think it's convenient. What do you think about it?
Thanks in advance!

**Comment by ddvk** [comment]
have to find some room somewhere

**Comment by PkW4v3** [comment]
Could put it under bookmarks button (in portrait mode)

Thanks for reply!

**Comment by PkW4v3** [comment]
![rM Screen 2020-09-26 21_08_19](https://user-images.githubusercontent.com/64780101/94423122-6c5ac480-0188-11eb-8cf8-3465ab023566.png)

Could you keep this pop up always visible with the current percentage? to remove it you could hold down in right corner.
Thanks!

**Comment by PkW4v3** [comment]
Any news?
I'm sorry for ask again, but I hope you can implement this thing.
Thanks!

**Comment by ddvk** [comment]
i added an initial prototype, the last icon (document menu) is now the battery icon (without the percentage). i think showing it on the screen is too obtrusive

**Comment by Tridens92** [comment]
A bit of feedback on the prototype.  If we're going to have this battery icon,

1) Please add charging status, as it's confusing if the stock rM battery icon on the home page indicates the device is charging but the hack one doesn't

2) Perhaps a toggle to allow the standard document icon, which could also move the battery status to the document menu rather than always being visible.  I miss the Document icon, and that the battery is just more distracting.  So this option would be great, if possible,

Thanks again for your incredible work, @ddvk !
