### ISSUE TITLE
ENHANCEMENT: In Zen mode, right button (or left for LH) to toggle select tool

### ISSUE THREAD

**Issue by LukeyBrown** [ddvk/remarkable-hacks#67]
I've been starting to use the select tool more and more for selective deletions (example: https://streamable.com/y05txd), and this would make a useful tool for note taking and sketching.

If there is anything that I can do to assist (basic JS is about the extent of my current knowledge), I'd be happy to help!

**Comment by Tridens92** [comment]
I'd actually suggest a modification of this potential enhancement.  I know there have been multiple suggestions for other toggles (i.e. Highlighter, etc.).  What about the possibility of, rather than assigning one toggle to the right button, a long press popped up a grid of potential toggle assignments (Select Tool, Highlighter, etc)?  One could then choose a custom function for the right button, which would be activated on a short press.  This would give more flexibility for the right button, and ability to change at will (select tool when writing or drawing, highlighter tool when reviewing/marking up docs, etc.).

**Comment by Tridens92** [comment]
@ddvk, I'm continuing to love this enhancement.  Thank you!  One potential suggestion.  I use the select tool as much as I do anything else.  Is it possible to add the Selection tool to this list of potential "tools" that can be assigned to the "last brush" on right button press, so we could toggle between writing and moving?

**Comment by Tridens92** [comment]
@ddvk, thanks *so much* for enabling these zen mode toggles!  I didn't even realize it had been added until today.  What a time-saver!

Any chance the above suggestion about adding Selection tool?

Either way, thanks again for your incredible work.

**Comment by ddvk** [comment]
covered by switich to last tool now

**Comment by alexbaharov** [comment]
I opened issue #114, as the toggle tool loses the "other tool" from memory if the left (toggle with errasor) button is pressed.

**Comment by Tridens92** [comment]
@alebaho , you beat me to the punch!  I was just logging in to report this bug. :)
